version: '3.8'

services:
  # Firewall (Correction OSPF et Tini)
  firewall:
    image: frrouting/frr:latest
    container_name: firewall
    privileged: true
    cap_add:
      - NET_ADMIN
    environment:
      - TINI_SUBREAPER=1
    networks:
      dmz_in:
        ipv4_address: 10.0.0.100
      dmz_out:
        ipv4_address: 10.32.0.100
      internal:
        ipv4_address: 10.64.0.253
    volumes:
      - ./frr-firewall:/etc/frr
    command: >
      bash -c '
      set -e && 
      mkdir -p /etc/frr &&
      echo "zebra=yes\nbgpd=no\nospfd=yes" > /etc/frr/daemons &&
      if [ ! -f /etc/frr/frr.conf ]; then
        echo "frr version 8.4\n        frr defaults traditional\n        hostname firewall\n        service integrated-vtysh-config\n        !\n        router ospf\n          ospf router-id 10.0.0.100\n          network 10.0.0.0/11 area 0\n          network 10.32.0.0/11 area 0\n          network 10.64.0.0/12 area 0\n        !\n        line vty\n        !" > /etc/frr/frr.conf;
      fi &&
      touch /etc/frr/vtysh.conf &&
      chown -R frr:frr /etc/frr &&
      /usr/lib/frr/watchfrr -d -F traditional zebra bgpd ospfd staticd &&
      sleep 10 &&
      tail -f /dev/null'

  # Router (Correction OSPF et Tini)
  router:
    image: frrouting/frr:latest
    container_name: router
    privileged: true
    cap_add:
      - NET_ADMIN
    environment:
      - TINI_SUBREAPER=1
    networks:
      dmz_in:
        ipv4_address: 10.0.0.101
      dmz_out:
        ipv4_address: 10.32.0.101
      internal:
        ipv4_address: 10.64.0.254
    volumes:
      - ./frr:/etc/frr
    command: >
      bash -c '
      set -e && 
      mkdir -p /etc/frr &&
      echo "zebra=yes\nbgpd=yes\nospfd=yes" > /etc/frr/daemons &&
      if [ ! -f /etc/frr/frr.conf ]; then
        echo "frr version 7.5\n        frr defaults traditional\n        hostname router\n        service integrated-vtysh-config\n        !\n        router ospf\n          ospf router-id 10.0.0.101\n          network 10.0.0.0/11 area 0\n          network 10.32.0.0/11 area 0\n          network 10.64.0.0/12 area 0\n        !\n        line vty\n        !" > /etc/frr/frr.conf;
      fi &&
      touch /etc/frr/vtysh.conf &&
      chown -R frr:frr /etc/frr &&
      /usr/lib/frr/watchfrr -d -F traditional zebra bgpd ospfd staticd &&
      sleep 10 &&
      tail -f /dev/null'
    healthcheck:
      test: ["CMD", "vtysh", "-c", "show ip ospf neighbor"]
      interval: 30s
      retries: 3

  # DNS
  dns:
    image: sameersbn/bind:latest
    container_name: dns
    privileged: true
    networks:
      dmz_in:
        ipv4_address: 10.0.0.2
    ports:
      - "15353:53/udp"
      - "15353:53/tcp"
    volumes:
      - ./bind:/data/bind
    command: >
      bash -c "
      set -e && export DEBIAN_FRONTEND=noninteractive && 
      apt update && apt install -y --reinstall iproute2 iputils-ping iptables net-tools && 
      if [ ! -f /data/bind/named.conf ]; then
        echo 'options {
          directory \"/var/cache/bind\";
          recursion yes;
          allow-query { any; };
          forwarders { 8.8.8.8; 8.8.4.4; };
        };' > /data/bind/named.conf;
      fi &&
      /sbin/entrypoint.sh"

  # DHCP
  dhcp:
    image: networkboot/dhcpd:latest
    container_name: dhcp
    privileged: true
    networks:
      dmz_in:
        ipv4_address: 10.0.0.3
    ports:
      - "6767:67/udp"
    volumes:
      - ./dhcp:/data
    command: >
      bash -c "
      set -e && export DEBIAN_FRONTEND=noninteractive && 
      apt update && apt install -y --reinstall iproute2 iputils-ping iptables net-tools && 
      if [ ! -f /data/dhcpd.conf ]; then
        echo 'subnet 10.0.0.0 netmask 255.255.255.0 {
          range 10.0.0.100 10.0.0.200;
          option routers 10.0.0.101;
          option domain-name-servers 10.0.0.2;
        }' > /data/dhcpd.conf;
      fi &&
      /entrypoint.sh"

  # Squid Proxy
  squid:
    image: sameersbn/squid:latest
    container_name: squid
    privileged: true
    networks:
      dmz_out:
        ipv4_address: 10.32.0.4
    ports:
      - "3128:3128"
    command: bash -c "set -e && export DEBIAN_FRONTEND=noninteractive && apt update && apt install -y --reinstall iproute2 iputils-ping iptables net-tools && /sbin/entrypoint.sh"

  # Syslog
  syslog:
    image: balabit/syslog-ng:latest
    container_name: syslog
    privileged: true
    networks:
      dmz_out:
        ipv4_address: 10.32.0.5
    command: bash -c "set -e && export DEBIAN_FRONTEND=noninteractive && apt update && apt install -y --reinstall iproute2 iputils-ping iptables net-tools && syslog-ng -F"

  # Workstation
  workstation:
    image: debian:12
    container_name: workstation
    privileged: true
    networks:
      internal:
        ipv4_address: 10.64.0.2
    command: >
      bash -c "
      set -e && export DEBIAN_FRONTEND=noninteractive && 
      apt update && 
      apt install -y --reinstall iproute2 iputils-ping iptables net-tools traceroute dnsutils isc-dhcp-client curl bsdutils netcat-openbsd && 
      ip route del default && ip route add default via 10.64.0.254 && 
      tail -f /dev/null"

networks:
  dmz_in:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/11
  dmz_out:
    driver: bridge
    ipam:
      config:
        - subnet: 10.32.0.0/11
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 10.64.0.0/12
